### ISSUE TITLE
docker paths

### ISSUE THREAD

**Issue by mikeyb** [phyro/etc-docker#1]
https://github.com/phyro/etc-docker/blob/2a12ad338825972d3e568d773cf6ca18ee95664a/docker-compose.yml#L7

https://github.com/phyro/etc-docker/blob/2a12ad338825972d3e568d773cf6ca18ee95664a/docker-compose.yml#L14

https://github.com/phyro/etc-docker/blob/2a12ad338825972d3e568d773cf6ca18ee95664a/docker-compose.yml#L23

Just me being nitpicky, but I would recommend using `./docker/Dockerfile-vault` (adding dot slash) for clarity

**Comment by phyro** [comment]
pushed to master
